In [1]:
import numpy as np
import pandas as pd
import os
from glob import glob
from tqdm.auto import tqdm

In [2]:
from readers import *

dataset_name, df = read_telco()#read_compas()

In [12]:
df

,x6_Yes,x7_Fiber optic,x2_No internet service,x5_Yes,x9_No,x0_No internet service,x4_No,SeniorCitizen,x7_DSL,x1_Mailed check,...,x8_No internet service,Dependents,x1_Electronic check,x6_No phone service,x8_Yes,x1_Bank transfer (automatic),x1_Credit card (automatic),x2_No,MonthlyCharges,y
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,29.85,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,56.95,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,53.85,1.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,42.30,0.0
4,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,70.70,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,84.80,0.0
7039,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,103.20,0.0
7040,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,29.60,0.0
7041,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,74.40,1.0
7042,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,105.65,0.0

In [10]:
from realkd.rules import RuleBoostingEstimator, XGBRuleEstimator
from sklearn.model_selection import train_test_split

X = df.drop(columns=['y'])#.values
y = df.y.replace(0, -1)#.values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

re = RuleBoostingEstimator(base_learner=XGBRuleEstimator())
re.fit(X_train, y_train)

KeyboardInterrupt:

In [ ]:
from sklearn.metrics import classification_report

y_pred = re.predict(X_test)

print(classification_report(y_true=y_test, y_pred=np.round(y_pred)))

In [ ]:
models = dict()

for max_rule in tqdm(range(1, 20+1)):
    re = RuleBoostingEstimator(num_rules=max_rule, base_learner=XGBRuleEstimator())
    re.fit(X_train, y_train)
    models[max_rule] = re
    y_pred = re.predict(X_test)
    print(max_rule)
    print(classification_report(y_true=y_test, y_pred=np.round(y_pred)))

## Apriori

In [16]:
dataset_name, df = read_magic(False)#read_compas()

df

,fWidth:,fConc:,fConc1:,fAlpha:,fM3Trans:,fAsym:,fSize:,fDist:,fM3Long:,fLength:,y
0,71.6420,0.0582,0.0325,35.1456,-48.9085,-142.8396,4.3904,286.9649,78.0804,123.5097,1
1,18.5717,0.3770,0.1932,1.8424,5.4656,25.4122,2.6304,145.4160,17.9303,25.8419,0
2,7.8292,0.7684,0.4696,36.7600,7.6089,21.6580,2.3462,177.9393,3.7830,8.2311,1
3,31.0349,0.1986,0.1063,1.9020,-13.7868,-41.5705,3.6720,358.0970,47.7730,87.3122,0
4,19.9587,0.3018,0.1591,7.6140,-21.8647,-122.1440,2.7404,241.4050,87.7162,105.7610,0
...,...,...,...,...,...,...,...,...,...,...,...
1995,7.6596,0.6380,0.4358,28.3315,9.3343,-4.6407,2.2159,226.1827,6.5507,18.2898,1
1996,47.6937,0.1220,0.0534,70.0625,35.8926,3.3522,3.4328,82.9808,-81.2962,90.2687,1
1997,44.2798,0.1331,0.0550,15.6243,33.7577,-53.6993,3.2843,153.5856,-21.9605,46.9412,1
1998,11.3629,0.4559,0.2579,34.9402,-11.7453,1.2535,2.4778,167.2160,-5.7541,28.0875,0
1999,19.4941,0.3753,0.2200,8.8963,-14.3853,8.9912,2.8522,89.1653,8.9581,27.5100,0

In [25]:
dataset_name, df = read_magic(False)#read_compas()

#to_encode = ['MonthlyCharges', 'TotalCharges', 'tenure']  # magic
to_encode = df.columns[:-1]

for col in to_encode:
    df[col] = pd.qcut(df[col], 10)

for col in df.columns:
    df[col] = df[col].apply(lambda x: f'{x}|{col}')

df.head()

,fWidth:,fConc:,fConc1:,fAlpha:,fM3Trans:,fAsym:,fSize:,fDist:,fM3Long:,fLength:,y
0,"(45.455, 228.038]|fWidth:","(0.015199999999999998, 0.155]|fConc:","(0.007, 0.0828]|fConc1:","(32.897, 45.873]|fAlpha:","(-205.89600000000002, -18.712]|fM3Trans:","(-363.339, -84.253]|fAsym:","(3.51, 5.012]|fSize:","(254.983, 298.114]|fDist:","(67.781, 227.817]|fM3Long:","(117.33, 290.927]|fLength:",1|y
1,"(17.03, 20.013]|fWidth:","(0.358, 0.412]|fConc:","(0.166, 0.198]|fConc1:","(-0.001, 2.061]|fAlpha:","(2.423, 6.685]|fM3Trans:","(18.667, 28.794]|fAsym:","(2.537, 2.647]|fSize:","(126.037, 154.888]|fDist:","(15.181, 19.782]|fM3Long:","(22.734, 26.739]|fLength:",0|y
2,"(-0.001, 9.274]|fWidth:","(0.66, 0.874]|fConc:","(0.376, 0.63]|fConc1:","(32.897, 45.873]|fAlpha:","(6.685, 9.942]|fM3Trans:","(18.667, 28.794]|fAsym:","(2.282, 2.431]|fSize:","(176.602, 194.268]|fDist:","(-8.914, 7.801]|fM3Long:","(4.2829999999999995, 19.134]|fLength:",1|y
3,"(29.599, 45.455]|fWidth:","(0.155, 0.209]|fConc:","(0.0828, 0.114]|fConc1:","(-0.001, 2.061]|fAlpha:","(-18.712, -12.516]|fM3Trans:","(-84.253, -36.028]|fAsym:","(3.51, 5.012]|fSize:","(298.114, 431.641]|fDist:","(44.334, 67.781]|fM3Long:","(86.493, 117.33]|fLength:",0|y
4,"(17.03, 20.013]|fWidth:","(0.257, 0.304]|fConc:","(0.14, 0.166]|fConc1:","(5.386, 9.219]|fAlpha:","(-205.89600000000002, -18.712]|fM3Trans:","(-363.339, -84.253]|fAsym:","(2.647, 2.752]|fSize:","(231.08, 254.983]|fDist:","(67.781, 227.817]|fM3Long:","(86.493, 117.33]|fLength:",0|y

In [26]:
from sklearn.model_selection import train_test_split

X = df#[['y']+list(df.columns)[:-1]].values.tolist()
y = df.y#.values.tolist()

X_train_df, X_test_df, y_train_df, y_test_df = train_test_split(X, y, stratify=y, random_state=42, test_size=.2)

X_train, X_test, y_train, y_test = (X_train_df.values.tolist(), X_test_df.values.tolist(), 
                                    y_train_df.values.tolist(), y_test_df.values.tolist())

X_train[0]

['(45.455, 228.038]|fWidth:',
 '(0.015199999999999998, 0.155]|fConc:',
 '(0.007, 0.0828]|fConc1:',
 '(32.897, 45.873]|fAlpha:',
 '(-205.89600000000002, -18.712]|fM3Trans:',
 '(-84.253, -36.028]|fAsym:',
 '(3.51, 5.012]|fSize:',
 '(254.983, 298.114]|fDist:',
 '(67.781, 227.817]|fM3Long:',
 '(117.33, 290.927]|fLength:',
 '1|y']

In [27]:
from fim import apriori
help(apriori)

Help on built-in function apriori in module fim:

apriori(...)
    apriori (tracts, target='s', supp=10, zmin=1, zmax=None, report='a',
             eval='x', agg='x', thresh=10, prune=None, algo='b', mode='',
             border=None)
    Find frequent item sets with the Apriori algorithm.
    tracts  transaction database to mine (mandatory)
            The database must be an iterable of transactions;
            each transaction must be an iterable of items;
            each item must be a hashable object.
            If the database is a dictionary, the transactions are
            the keys, the values their (integer) multiplicities.
    target  type of frequent item sets to find     (default: s)
            s/a   sets/all   all     frequent item sets
            c     closed     closed  frequent item sets
            m     maximal    maximal frequent item sets
            g     gens       generators
            r     rules      association rules
    supp    minimum support of an item set         (default: 10)
            (positive: percentage, negative: absolute number)
    conf    minimum confidence of an assoc. rule   (default: 80%)
    zmin    minimum number of items per item set   (default: 1)
    zmax    maximum number of items per item set   (default: no limit)
    report  values to report with an item set      (default: a)
            a     absolute item set support (number of transactions)
            s     relative item set support as a fraction
            S     relative item set support as a percentage
            e     value of item set evaluation measure
            E     value of item set evaluation measure as a percentage
            (     combine values in a tuple (must be first character)
            [     combine values in a list  (must be first character)
            #     pattern spectrum as a dictionary  (no patterns)
            =     pattern spectrum as a list        (no patterns)
            |     pattern spectrum as three columns (no patterns)
            for target 'r' (association rules) also available:
            b     absolute body set  support (number of transactions)
            x     relative body set  support as a fraction
            X     relative body set  support as a percentage
            h     absolute head item support (number of transactions)
            y     relative head item support as a fraction
            Y     relative head item support as a percentage
            c     rule confidence as a fraction
            C     rule confidence as a percentage
            l     lift value of a rule (confidence/prior)
            L     lift value of a rule as a percentage
            Q     support of the empty set (total number of transactions)
    eval    measure for item set evaluation        (default: x)
            x     none       no measure / zero (default)
            b     ldratio    binary logarithm of support quotient       (+)
            c     conf       rule confidence                            (+)
            d     confdiff   absolute confidence difference to prior    (+)
            l     lift       lift value (confidence divided by prior)   (+)
            a     liftdiff   absolute difference of lift value to 1     (+)
            q     liftquot   difference of lift quotient to 1           (+)
            v     cvct       conviction (inverse lift for negated head) (+)
            e     cvctdiff   absolute difference of conviction to 1     (+)
            r     cvctquot   difference of conviction quotient to 1     (+)
            k     cprob      conditional probability ratio              (+)
            j     import     importance (binary log. of prob. ratio)    (+)
            z     cert       certainty factor (relative conf. change)   (+)
            n     chi2       normalized chi^2 measure                   (+)
            p     chi2pval   p-value from (unnormalized) chi^2 measure  (-)
            y     yates      normalized chi^2 with Yates' correction    (+)
            t     yatespval  p-value from Yates-corrected chi^2 measure (-)
            i     info       information difference to prior            (+)
            g     infopval   p-value from G statistic/info. difference  (-)
            f     fetprob    Fisher's exact test (table probability)    (-)
            h     fetchi2    Fisher's exact test (chi^2 measure)        (-)
            m     fetinfo    Fisher's exact test (mutual information)   (-)
            s     fetsupp    Fisher's exact test (support)              (-)
            Measures marked with (+) must meet or exceed the threshold,
            measures marked with (-) must not exceed the threshold
            in order for the item set to be reported.
    agg     evaluation measure aggregation mode    (default: x)
            x     none       no aggregation (use first value)
            m     min        minimum of individual measure values
            n     max        maximum of individual measure values
            a     avg        average of individual measure values
    thresh  threshold for evaluation measure       (default: 10%)
    prune   min. size for evaluation filtering     (default: no pruning)
            = 0   backward filtering       (no subset check)
            < 0   weak   forward filtering (one subset  must qualify)
            > 0   strong forward filtering (all subsets must qualify)
    algo    algorithm variant to use               (default: a)
            b     basic      standard algorithm (only choice)
    mode    operation mode indicators/flags        (default: None)
            x     do not use perfect extension pruning
            t/T   do not organize transactions as a prefix tree
            y     a-posteriori pruning of infrequent item sets
            z     invalidate evaluation below expected support
            o     use original rule support definition (body & head)
    border  support border for filtering item sets (default: None)
            Must be a list or tuple of (absolute) minimum support values
            per item set size (by which the list/tuple is indexed).
    appear  dictionary mapping items to item appearance indicators,
            with the key None referring to the default item appearance.
            (If None does not occur as a key or no dictionary is given,
            the default item appearance indicator is 'both'.)
            This parameter is only used if the target type is rules.
            * item may not appear anywhere in a rule:
              '-', 'n', 'none', 'neither', 'ignore'
            * item may appear only in rule body/antecedent:
              'i', 'in', 'inp', 'input', 'b', 'body',
              'a', 'ante', 'antecedent'
            * item may appear only in rule head/consequent:
              'o', 'out',      'output', 'h', 'head',
              'c', 'cons', 'consequent'
            * item may appear anywhere in a rule:
              'io', 'i&o', 'inout', 'in&out', 'bh', 'b&h', 'both'
    returns if report is not in ['#','=','|']:
              if the target is association rules:
                a list of rules (i.e. tuples with two or more elements),
                each consisting of a head/consequent item, a tuple with
                a body/antecedent item set, and the values selected by
                the parameter 'report', which may be combined into a
                tuple or a list if report[0] is '(' or '[', respectively.
              if the target is a type of item sets:
                a list of patterns (i.e. tuples with one or more elements),
                each consisting of a tuple with a found frequent item set
                and the values selected by the parameter 'report', which
                may be combined into a tuple or list if report[0] is '('
                or '[', respectively
            if report in ['#','=','|']:
              a pattern spectrum as a dictionary mapping pattern sizes
              to the corresponding occurrence support ranges, as a list
              of triplets (size, min. support, max. support) or as three
              columns for sizes and minimum and maximum support values

In [38]:
supp = 5
zmin = 2

rules = apriori(X_train, target="r", supp=supp, zmin=zmin, conf=80, report="aScl")
rules_df = pd.DataFrame(rules, columns=["consequent", "antecedent", "abs_support", "%_support", "confidence", "lift"])

rules_df.sort_values(by="lift", axis=0, ascending=False)

,consequent,antecedent,abs_support,%_support,confidence,lift
1,"(0.66, 0.874]|fConc:","((1.9400000000000002, 2.282]|fSize:, (0.376, 0...",82,5.1250,0.953488,9.906373
7,"(0.015199999999999998, 0.155]|fConc:","((3.51, 5.012]|fSize:, (0.007, 0.0828]|fConc1:)",96,6.0000,0.969697,9.577254
14,"(0.007, 0.0828]|fConc1:","((45.455, 228.038]|fWidth:, (0.015199999999999...",83,5.1875,0.943182,9.491138
12,"(0.007, 0.0828]|fConc1:","((45.455, 228.038]|fWidth:, (0.015199999999999...",76,4.7500,0.938272,9.441727
13,"(0.015199999999999998, 0.155]|fConc:","((45.455, 228.038]|fWidth:, (0.007, 0.0828]|fC...",83,5.1875,0.954023,9.422449
11,"(0.015199999999999998, 0.155]|fConc:","((45.455, 228.038]|fWidth:, (0.007, 0.0828]|fC...",76,4.7500,0.950000,9.382716
3,"(0.66, 0.874]|fConc:","((0.376, 0.63]|fConc1:, (4.2829999999999995, 1...",74,4.6250,0.891566,9.263026
21,"(0.015199999999999998, 0.155]|fConc:","((0.007, 0.0828]|fConc1:, 1|y)",98,6.1250,0.933333,9.218107
23,"(0.015199999999999998, 0.155]|fConc:","((0.007, 0.0828]|fConc1:,)",146,9.1250,0.918239,9.069027
24,"(0.007, 0.0828]|fConc1:","((0.015199999999999998, 0.155]|fConc:,)",146,9.1250,0.901235,9.069027
8,"(0.007, 0.0828]|fConc1:","((3.51, 5.012]|fSize:, (0.015199999999999998, ...",96,6.0000,0.897196,9.028390
22,"(0.007, 0.0828]|fConc1:","((0.015199999999999998, 0.155]|fConc:, 1|y)",98,6.1250,0.890909,8.965123
2,"(0.376, 0.63]|fConc1:","((0.66, 0.874]|fConc:, (4.2829999999999995, 19...",74,4.6250,0.850575,8.505747
6,"(45.455, 228.038]|fWidth:","((3.51, 5.012]|fSize:, 1|y)",74,4.6250,0.822222,8.273934
0,"(0.376, 0.63]|fConc1:","((0.66, 0.874]|fConc:, (1.9400000000000002, 2....",82,5.1250,0.811881,8.118812
18,1|y,"((45.455, 228.038]|fWidth:, (117.33, 290.927]|...",107,6.6875,1.000000,2.000000
28,1|y,"((117.33, 290.927]|fLength:, (-331.78099999999...",94,5.8750,0.989474,1.978947
19,1|y,"((45.455, 228.038]|fWidth:, (-331.780999999999...",86,5.3750,0.988506,1.977011
29,1|y,"((117.33, 290.927]|fLength:,)",159,9.9375,0.969512,1.939024
25,1|y,"((-363.339, -84.253]|fAsym:, (117.33, 290.927]...",95,5.9375,0.959596,1.919192
16,1|y,"((45.455, 228.038]|fWidth:, (20.35, 179.851]|f...",84,5.2500,0.954545,1.909091
20,1|y,"((45.455, 228.038]|fWidth:,)",150,9.3750,0.943396,1.886792
30,1|y,"((-331.78099999999995, -47.26]|fM3Long:,)",154,9.6250,0.933333,1.866667
17,1|y,"((45.455, 228.038]|fWidth:, (0.015199999999999...",81,5.0625,0.920455,1.840909
15,1|y,"((45.455, 228.038]|fWidth:, (0.007, 0.0828]|fC...",80,5.0000,0.919540,1.839080
10,1|y,"((45.455, 228.038]|fWidth:, (0.007, 0.0828]|fC...",76,4.7500,0.915663,1.831325
5,1|y,"((3.51, 5.012]|fSize:, (45.455, 228.038]|fWidth:)",74,4.6250,0.902439,1.804878
27,0|y,"((-0.001, 2.061]|fAlpha:,)",142,8.8750,0.887500,1.775000
4,0|y,"((2.061, 5.386]|fAlpha:,)",132,8.2500,0.840764,1.681529
26,1|y,"((-363.339, -84.253]|fAsym:,)",133,8.3125,0.836478,1.672956
9,1|y,"((59.452, 75.932]|fAlpha:,)",130,8.1250,0.822785,1.645570

In [30]:
rules_df[rules_df.consequent.apply(lambda x: f'{x}'.endswith('|y'))]

,consequent,antecedent,abs_support,%_support,confidence,lift
4,0|y,"((2.061, 5.386]|fAlpha:,)",132,8.2500,0.840764,1.681529
5,1|y,"((3.51, 5.012]|fSize:, (45.455, 228.038]|fWidth:)",74,4.6250,0.902439,1.804878
9,1|y,"((59.452, 75.932]|fAlpha:,)",130,8.1250,0.822785,1.645570
10,1|y,"((45.455, 228.038]|fWidth:, (0.007, 0.0828]|fC...",76,4.7500,0.915663,1.831325
15,1|y,"((45.455, 228.038]|fWidth:, (0.007, 0.0828]|fC...",80,5.0000,0.919540,1.839080
16,1|y,"((45.455, 228.038]|fWidth:, (20.35, 179.851]|f...",84,5.2500,0.954545,1.909091
17,1|y,"((45.455, 228.038]|fWidth:, (0.015199999999999...",81,5.0625,0.920455,1.840909
18,1|y,"((45.455, 228.038]|fWidth:, (117.33, 290.927]|...",107,6.6875,1.000000,2.000000
19,1|y,"((45.455, 228.038]|fWidth:, (-331.780999999999...",86,5.3750,0.988506,1.977011
20,1|y,"((45.455, 228.038]|fWidth:,)",150,9.3750,0.943396,1.886792
25,1|y,"((-363.339, -84.253]|fAsym:, (117.33, 290.927]...",95,5.9375,0.959596,1.919192
26,1|y,"((-363.339, -84.253]|fAsym:,)",133,8.3125,0.836478,1.672956
27,0|y,"((-0.001, 2.061]|fAlpha:,)",142,8.8750,0.887500,1.775000
28,1|y,"((117.33, 290.927]|fLength:, (-331.78099999999...",94,5.8750,0.989474,1.978947
29,1|y,"((117.33, 290.927]|fLength:,)",159,9.9375,0.969512,1.939024
30,1|y,"((-331.78099999999995, -47.26]|fM3Long:,)",154,9.6250,0.933333,1.866667

In [31]:
def codifica(df_rules, df):
    rules = df_rules.antecedent.unique()
    X_cod = np.ones((len(df), len(rules))).astype(np.bool_)
    for i, rule_list in enumerate(rules):
        for rule in rule_list:
            feat = rule.split('|')[-1]
            X_cod[:, i] &= (df[feat] == rule).values
    return X_cod, rules

In [32]:
rules_df_cod = rules_df[rules_df.antecedent.apply(lambda x: '|y' not in str(x)) & rules_df.consequent.apply(lambda x: '|y' not in x)]

X_train_cod, rules = codifica(df_rules=rules_df_cod, df=X_train_df)
X_test_cod, _ = codifica(df_rules=rules_df_cod, df=X_test_df)

In [33]:
rules_df_cod

,consequent,antecedent,abs_support,%_support,confidence,lift
0,"(0.376, 0.63]|fConc1:","((0.66, 0.874]|fConc:, (1.9400000000000002, 2....",82,5.1250,0.811881,8.118812
1,"(0.66, 0.874]|fConc:","((1.9400000000000002, 2.282]|fSize:, (0.376, 0...",82,5.1250,0.953488,9.906373
2,"(0.376, 0.63]|fConc1:","((0.66, 0.874]|fConc:, (4.2829999999999995, 19...",74,4.6250,0.850575,8.505747
3,"(0.66, 0.874]|fConc:","((0.376, 0.63]|fConc1:, (4.2829999999999995, 1...",74,4.6250,0.891566,9.263026
7,"(0.015199999999999998, 0.155]|fConc:","((3.51, 5.012]|fSize:, (0.007, 0.0828]|fConc1:)",96,6.0000,0.969697,9.577254
8,"(0.007, 0.0828]|fConc1:","((3.51, 5.012]|fSize:, (0.015199999999999998, ...",96,6.0000,0.897196,9.028390
13,"(0.015199999999999998, 0.155]|fConc:","((45.455, 228.038]|fWidth:, (0.007, 0.0828]|fC...",83,5.1875,0.954023,9.422449
14,"(0.007, 0.0828]|fConc1:","((45.455, 228.038]|fWidth:, (0.015199999999999...",83,5.1875,0.943182,9.491138
23,"(0.015199999999999998, 0.155]|fConc:","((0.007, 0.0828]|fConc1:,)",146,9.1250,0.918239,9.069027
24,"(0.007, 0.0828]|fConc1:","((0.015199999999999998, 0.155]|fConc:,)",146,9.1250,0.901235,9.069027

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

le = LabelEncoder()
y_train_num = le.fit_transform(y_train)
y_test_num = le.transform(y_test)


lr = LogisticRegression()
lr.fit(X_train_cod, y_train_num)

y_pred = lr.predict(X_test_cod)

print(classification_report(y_true=y_test_num, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.52      0.94      0.67       200
           1       0.72      0.14      0.23       200

    accuracy                           0.54       400
   macro avg       0.62      0.54      0.45       400
weighted avg       0.62      0.54      0.45       400

In [35]:
from sklearn.tree import DecisionTreeClassifier, export_text

rt = DecisionTreeClassifier(max_depth=1)
rt.fit(X_train_cod, y_train_num)

y_pred = rt.predict(X_test_cod)

print(classification_report(y_true=y_test_num, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.52      0.99      0.69       200
           1       0.91      0.10      0.18       200

    accuracy                           0.55       400
   macro avg       0.72      0.55      0.43       400
weighted avg       0.72      0.55      0.43       400

In [36]:
print(export_text(rt, feature_names=rules))

|--- ('(45.455, 228.038]|fWidth:', '(0.015199999999999998, 0.155]|fConc:') <= 0.50
|   |--- class: 0
|--- ('(45.455, 228.038]|fWidth:', '(0.015199999999999998, 0.155]|fConc:') >  0.50
|   |--- class: 1

In [37]:
rules_df_cod

,consequent,antecedent,abs_support,%_support,confidence,lift
0,"(0.376, 0.63]|fConc1:","((0.66, 0.874]|fConc:, (1.9400000000000002, 2....",82,5.1250,0.811881,8.118812
1,"(0.66, 0.874]|fConc:","((1.9400000000000002, 2.282]|fSize:, (0.376, 0...",82,5.1250,0.953488,9.906373
2,"(0.376, 0.63]|fConc1:","((0.66, 0.874]|fConc:, (4.2829999999999995, 19...",74,4.6250,0.850575,8.505747
3,"(0.66, 0.874]|fConc:","((0.376, 0.63]|fConc1:, (4.2829999999999995, 1...",74,4.6250,0.891566,9.263026
7,"(0.015199999999999998, 0.155]|fConc:","((3.51, 5.012]|fSize:, (0.007, 0.0828]|fConc1:)",96,6.0000,0.969697,9.577254
8,"(0.007, 0.0828]|fConc1:","((3.51, 5.012]|fSize:, (0.015199999999999998, ...",96,6.0000,0.897196,9.028390
13,"(0.015199999999999998, 0.155]|fConc:","((45.455, 228.038]|fWidth:, (0.007, 0.0828]|fC...",83,5.1875,0.954023,9.422449
14,"(0.007, 0.0828]|fConc1:","((45.455, 228.038]|fWidth:, (0.015199999999999...",83,5.1875,0.943182,9.491138
23,"(0.015199999999999998, 0.155]|fConc:","((0.007, 0.0828]|fConc1:,)",146,9.1250,0.918239,9.069027
24,"(0.007, 0.0828]|fConc1:","((0.015199999999999998, 0.155]|fConc:,)",146,9.1250,0.901235,9.069027